import test from 'node:test';
import assert from 'node:assert/strict';
import { parsePackageJson, parsePackageLock, parseYarnLock, parsePnpmLock } from '../src/parse/npm.js';
import { parseRequirements, parsePyproject, normalizeName, nameFromRequirement } from '../src/parse/pypi.js';
import { parseCargoToml, parseCargoLock } from '../src/parse/cargo.js';
import { parse as parseToml } from '../src/parse/toml-lite.js';

// ---------------------------------------------------------------------------
// package.json
// ---------------------------------------------------------------------------

test('package.json: dort bolumu de okur', () => {
  const deps = parsePackageJson(
    JSON.stringify({
      dependencies: { a: '^1.0.0' },
      devDependencies: { b: '^2.0.0' },
      optionalDependencies: { c: '^3.0.0' },
      peerDependencies: { d: '^4.0.0' },
    })
  );
  const byName = Object.fromEntries(deps.map((d) => [d.name, d.section]));
  assert.deepEqual(byName, { a: 'prod', b: 'dev', c: 'optional', d: 'peer' });
});

test('package.json: UTF-8 BOM uzerinde de calisir', () => {
  const text = '\uFEFF' + JSON.stringify({ dependencies: { express: '^4.0.0' } });
  const deps = parsePackageJson(text);
  assert.equal(deps.length, 1);
  assert.equal(deps[0].name, 'express');
});

test('package.json: bozuk JSON bos liste dondurur (cokmemesi)', () => {
  assert.deepEqual(parsePackageJson('{not json'), []);
  assert.deepEqual(parsePackageJson(''), []);
  assert.deepEqual(parsePackageJson(null), []);
});

test('package.json: yerel bagimliliklari atlar', () => {
  const deps = parsePackageJson(
    JSON.stringify({
      dependencies: { local: 'file:../local', link: 'link:../x', normal: '^1.0.0' },
    })
  );
  assert.deepEqual(deps.map((d) => d.name), ['normal']);
});

// ---------------------------------------------------------------------------
// package-lock.json
// ---------------------------------------------------------------------------

test('package-lock v3: packages alanindan okur', () => {
  const lock = {
    lockfileVersion: 3,
    packages: {
      '': { name: 'root', dependencies: { express: '^4.0.0' } },
      'node_modules/express': { version: '4.21.2' },
      'node_modules/lodash': { version: '4.17.21' },
      'node_modules/@types/node': { version: '20.0.0' },
      'node_modules/.pnpm/whatever': { version: '1.0.0' },
      'node_modules/local-pkg': { version: '1.0.0', resolved: 'file:../local' },
    },
  };
  const deps = parsePackageLock(JSON.stringify(lock));
  const names = deps.map((d) => d.name);
  assert.ok(names.includes('express'));
  assert.ok(names.includes('lodash'));
  assert.ok(names.includes('@types/node'));
  assert.ok(!names.includes('local-pkg'), 'yerel paket atlanmali');
  const express = deps.find((d) => d.name === 'express');
  assert.equal(express.version, '4.21.2');
});

test('package-lock v3: kok paket (bos anahtar) sayilmaz', () => {
  const lock = { packages: { '': { name: 'root', version: '1.0.0' } } };
  assert.deepEqual(parsePackageLock(JSON.stringify(lock)), []);
});

test('package-lock v1: ic ice dependencies yurur', () => {
  const lock = {
    lockfileVersion: 1,
    dependencies: {
      express: {
        version: '4.21.2',
        dependencies: { debug: { version: '4.4.0' } },
      },
      lodash: { version: '4.17.21' },
    },
  };
  const deps = parsePackageLock(JSON.stringify(lock));
  const names = deps.map((d) => d.name).sort();
  assert.deepEqual(names, ['debug', 'express', 'lodash']);
});

test('package-lock: BOM ve bozuk dosya', () => {
  assert.deepEqual(parsePackageLock('\uFEFF' + JSON.stringify({ packages: { 'node_modules/a': { version: '1.0.0' } } })), [
    { name: 'a', version: '1.0.0', dev: false, optional: false },
  ]);
  assert.deepEqual(parsePackageLock('{bozuk'), []);
});

// ---------------------------------------------------------------------------
// yarn.lock
// ---------------------------------------------------------------------------

test('yarn.lock v1: klasik bicim', () => {
  const text = `
# THIS IS AN AUTOGENERATED FILE
"@babel/code-frame@^7.0.0":
  version "7.24.0"
  resolved "https://registry.yarnpkg.com/..."

chalk@^4.1.0, chalk@^4.1.2:
  version "4.1.2"
  resolved "https://registry.yarnpkg.com/..."

debug@npm:debug@^4.3.0:
  version "4.3.4"
`;
  const deps = parseYarnLock(text);
  const names = deps.map((d) => d.name);
  assert.ok(names.includes('@babel/code-frame'));
  assert.ok(names.includes('chalk'));
  assert.ok(names.includes('debug'));
  assert.equal(deps.find((d) => d.name === 'chalk').version, '4.1.2');
  assert.equal(deps.filter((d) => d.name === 'chalk').length, 1, 'ayni paket birden fazla anahtarda tektir');
});

test('yarn.lock: boss ve anlasilmaz metin patlamaz', () => {
  assert.deepEqual(parseYarnLock(''), []);
  assert.deepEqual(parseYarnLock('sadece bir satir'), []);
});

// ---------------------------------------------------------------------------
// pnpm-lock.yaml
// ---------------------------------------------------------------------------

test('pnpm-lock v9: packages altindaki anahtarlari okur', () => {
  const text = `
lockfileVersion: '9.0'

packages:

  express@4.21.2:
    resolution: {integrity: sha512-abc}

  lodash@4.17.21:
    resolution: {integrity: sha512-def}

  '@types/node@20.0.0':
    resolution: {integrity: sha512-xyz}

snapshots:

  express@4.21.2: {}
`;
  const deps = parsePnpmLock(text);
  const names = deps.map((d) => d.name);
  assert.ok(names.includes('express'));
  assert.ok(names.includes('lodash'));
  assert.ok(names.includes('@types/node'));
  assert.equal(deps.filter((d) => d.name === 'express').length, 1, 'snapshots tekrarini saymaz');
  assert.equal(deps.find((d) => d.name === 'express').version, '4.21.2');
});

test('pnpm-lock: peer notasyonunu ayristirir', () => {
  const text = `
packages:

  foo@1.2.3(bar@2.0.0):
    resolution: {integrity: sha512-abc}
`;
  const deps = parsePnpmLock(text);
  assert.equal(deps.length, 1);
  assert.equal(deps[0].name, 'foo');
  assert.equal(deps[0].version, '1.2.3');
});

// ---------------------------------------------------------------------------
// Python
// ---------------------------------------------------------------------------

test('normalizeName: PEP 503 uyumlu', () => {
  assert.equal(normalizeName('Django_Tornado'), 'django-tornado');
  assert.equal(normalizeName('zope.interface'), 'zope-interface');
  assert.equal(normalizeName('requests'), 'requests');
});

test('nameFromRequirement: surum belirtecleri', () => {
  assert.equal(nameFromRequirement('requests>=2.0'), 'requests');
  assert.equal(nameFromRequirement('requests == 2.28.0'), 'requests');
  assert.equal(nameFromRequirement('requests[security]>=2.0'), 'requests');
  assert.equal(nameFromRequirement('requests~=2.28'), 'requests');
  assert.equal(nameFromRequirement('Django'), 'django');
  assert.equal(nameFromRequirement('-r other.txt'), null);
  assert.equal(nameFromRequirement(''), null);
});

test('requirements.txt: yorum, bos satir ve devam satiri', () => {
  const text = `
# yorum satiri
requests>=2.28.0

flask==3.0.0
  # girintili yorum
numpy \\
    >=1.24
-r diger.txt
-e ./
--index-url https://example.com/simple
`;
  const deps = parseRequirements(text);
  const names = deps.map((d) => d.name);
  assert.deepEqual(names, ['requests', 'flask', 'numpy']);
});

test('requirements.txt: BOM ve tekrarlari', () => {
  const deps = parseRequirements('\uFEFFrequests\nrequests\n');
  assert.equal(deps.length, 1);
});

test('pyproject.toml: PEP 621 dependencies', () => {
  const text = `
[project]
name = "ornek"
dependencies = [
  "requests>=2.28",
  "flask==3.0.0",
]

[project.optional-dependencies]
dev = ["pytest>=7"]
`;
  const deps = parsePyproject(text);
  const names = deps.map((d) => d.name);
  assert.ok(names.includes('requests'));
  assert.ok(names.includes('flask'));
  if (!names.includes('pytest')) {
    // optional-dependencies desteklenmiyorsa en azindan patlamamali
    assert.ok(names.length >= 2);
  }
});

test('pyproject.toml: Poetry bolumu', () => {
  const text = `
[tool.poetry]
name = "ornek"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28"
`;
  const deps = parsePyproject(text);
  const names = deps.map((d) => d.name);
  assert.ok(names.includes('requests'), 'python anahtari hedef degil ama requests olmali');
});

test('pyproject.toml: bozuk TOML bos liste', () => {
  assert.deepEqual(parsePyproject('[project'), []);
});

// ---------------------------------------------------------------------------
// Cargo / TOML
// ---------------------------------------------------------------------------

test('Cargo.toml: dependencies bolumu', () => {
  const text = `
[package]
name = "ornek"
version = "0.1.0"

[dependencies]
serde = "1.0"
tokio = { version = "1", features = ["full"] }
rand = { workspace = true }

[dev-dependencies]
criterion = "0.5"
`;
  const deps = parseCargoToml(text);
  const names = deps.map((d) => d.name);
  assert.ok(names.includes('serde'));
  assert.ok(names.includes('tokio'));
  assert.ok(names.includes('criterion'), 'dev-dependencies de toplanir');
  assert.ok(!names.includes('name'), 'package bolumu karistirilmaz');
  const tokio = deps.find((d) => d.name === 'tokio');
  assert.equal(tokio.range, '1');
});

test('Cargo.toml: BOM uzerinde de calisir', () => {
  const deps = parseCargoToml('\uFEFF[dependencies]\nserde = "1.0"\n');
  assert.equal(deps.length, 1);
  assert.equal(deps[0].name, 'serde');
});

test('Cargo.lock: paket listesi ve kaynakli local paketler', () => {
  const text = `
version = 3

[[package]]
name = "serde"
version = "1.0.203"

[[package]]
name = "ornek"
version = "0.1.0"
dependencies = ["serde"]

[[package]]
name = "local"
version = "0.1.0"
source = "path+file:///../local"
`;
  const deps = parseCargoLock(text);
  const names = deps.map((d) => d.name);
  assert.ok(names.includes('serde'));
  assert.ok(!names.includes('local'), 'path kaynakli paket atlanmali');
  assert.equal(deps.find((d) => d.name === 'serde').version, '1.0.203');
});

test('toml-lite: yorum, diziler ve ic tablolar', () => {
  const doc = parseToml(`
# yorum
top = "deger"  # satir ici yorum
sayi = 42
dizi = ["a", "b", "c"]
inline = { x = 1, y = "iki" }

[bolum]
alt = "deger"

[[liste]]
ad = "bir"

[[liste]]
ad = "iki"
`);
  assert.equal(doc.top, 'deger');
  assert.equal(doc.sayi, 42);
  assert.deepEqual(doc.dizi, ['a', 'b', 'c']);
  assert.equal(doc.inline.x, 1);
  assert.equal(doc.bolum.alt, 'deger');
  assert.equal(doc.liste.length, 2);
  assert.equal(doc.liste[1].ad, 'iki');
});
